### ISSUE TITLE
安装脚本有问题

### ISSUE THREAD

**Issue by dong-dong6** [LinWin-Cloud/Easy-DDOS#2]
Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-126-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

7 updates can be applied immediately.
7 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

New release '24.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

========================
This image built by AkileCloud.
Build time: 2023-09-10 19:07:25 UTC.
Last login: Thu Dec  5 13:12:50 2024 from 36.135.125.17
root@hkg11-20241006232318ea4b14:~# git clone https://gitee.com/LinWin-Cloud/easy-ddos
Cloning into 'easy-ddos'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 258 (delta 127), reused 258 (delta 127), pack-reused 0
Receiving objects: 100% (258/258), 452.79 KiB | 1.25 MiB/s, done.
Resolving deltas: 100% (127/127), done.
root@hkg11-20241006232318ea4b14:~# cd easy-ddos
root@hkg11-20241006232318ea4b14:~/easy-ddos# python3 ./install_lib.py
Traceback (most recent call last):
  File "/root/easy-ddos/./install_lib.py", line 5, in <module>
    read_lib = read(open_lib)
NameError: name 'read' is not defined
root@hkg11-20241006232318ea4b14:~/easy-ddos# python ./install_lib.py
-bash: python: command not found
root@hkg11-20241006232318ea4b14:~/easy-ddos# python3 ./install_lib.py
Traceback (most recent call last):
  File "/root/easy-ddos/./install_lib.py", line 5, in <module>
    read_lib = read(open_lib)
NameError: name 'read' is not defined

**Comment by 2797613519** [comment]
找到install_lib.py文件，第5行更改为
read_lib = open_lib.read()
即可
